### ISSUE TITLE
批量发送消息 bug

### ISSUE THREAD

**Issue by Openfan-Alex** [DevOpen-Club/bot-tools#23]
请尽快修复sendMassage功能中发送消息剩余最后二十人左右发送进度卡住的bug

**Comment by kaikaibenkai** [comment]
此问题存在于旧版机器人工具中，此仓库是新版机器人工具代码仓库

---

注：新版如果有此功能，这个 bug 应该不会再出现 :smile: 新版 SDK 取消了部分抽象

**Comment by Openfan-Alex** [comment]
旧版机器人工具并没有存储库吗



发自139邮箱






------------------ 原始邮件 ------------------




 
 发件人: KaiKai  ***@***.***>
 

 
 发送时间: 2023-12-04 21:23:38
 

 
 收件人: DevOpen-Club/bot-tools  ***@***.***> 
 

 
 抄送: alexxin139  ***@***.***>,Author  ***@***.***> 
 

 
 主题: Re: [DevOpen-Club/bot-tools] bug (Issue #23)
 





 此问题存在于旧版机器人工具中，此仓库是新版机器人工具代码仓库

**Comment by kaikaibenkai** [comment]
https://github.com/Starlight-Dev-Team/fanbook-bot-tools
